# Generated by Django 4.2.23 on 2025-07-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False)),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='logger.daylog')),
            ],
        ),
    ]
