# Generated by Django 4.2.23 on 2025-07-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='finish_time',
            new_name='trip_finish_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_time',
            new_name='trip_start_time',
        ),
    ]
